### ISSUE TITLE
Quantumult X运行备份Gist脚本无效

### ISSUE THREAD

**Issue by godlikeanyone** [dompling/Script#4]
- BoxJS中已配置用户名和token，点击备份Gist之后日志如下图：
![photo_2022-04-26_21-22-40.jpg](https://s2.loli.net/2022/04/26/HMnzJbtxr7AdiZB.jpg)  

- 手动添加本地定时任务后仍运行失败，并且Quantumult X没有log：
![photo_2022-04-26_21-22-35.jpg](https://s2.loli.net/2022/04/26/RYQKZ6PdTMH4kJ1.jpg)

**Comment by dompling** [comment]
@godlikeanyone 这边测试是可以的

**Comment by godlikeanyone** [comment]
> @godlikeanyone 这边测试是可以的

恢复备份log会显示未找到备份，但是备份log一点信息都没有。我尝试重新创建了token并给了gist权限，还是没有信息，备份也失败了。

**Comment by dompling** [comment]
@godlikeanyone 可能是数据太大导致的

**Comment by godlikeanyone** [comment]
> @godlikeanyone 可能是数据太大导致的

除了BoxJS内置的脚本，只添加了iRingo的Siri修改和天气修改这两个，数据不应该很大。

**Comment by iEngne** [comment]
同样的情况，也只添加了iRingo的一个订阅，无法备份，log中日志也是空的

**Comment by gdyan2001** [comment]
同样的情况

**Comment by dompling** [comment]
@gdyan2001

**Comment by dompling** [comment]
@gdyan2001

**Comment by Mattraks** [comment]
修一下吧

**Comment by dompling** [comment]
@Mattraks 日志看看

**Comment by Mattraks** [comment]
> @Mattraks 日志看看

跟上面第一张图一样

**Comment by dompling** [comment]
> 

我用 qx 测试过了，目前没有遇到类似的问题，可以的话可以去电报群录屏反馈一下[https://t.me/+ViT7uEUrIUV0B_iy](url)

> > @Mattraks 日志看看
> 
> 跟上面第一张图一样

**Comment by Mattraks** [comment]
我使用的是loon反复试了几次都是一样的结果

**Comment by dompling** [comment]
> * BoxJS中已配置用户名和token，点击备份Gist之后日志如下图：
>   ![photo_2022-04-26_21-22-40.jpg](https://camo.githubusercontent.com/f006d6fff36f8bd85f11b3e46f74d51d099d96eedaccde8e2c12139c7d6534f1/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30342f32362f484d6e7a4a62747872374164695a422e6a7067)
> * 手动添加本地定时任务后仍运行失败，并且Quantumult X没有log：
>   ![photo_2022-04-26_21-22-35.jpg](https://camo.githubusercontent.com/75fcad861646e45af4912bdb8e4539c7380b5c0433767677df8d793cd27c77d2/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30342f32362f5259514b5a365064544d48346b4a312e6a7067)

这种问题，我刚刚测试遇到的是

> 我使用的是loon反复试了几次都是一样的结果

我刚刚测试过，可能只会是 gist 配置错误的情况下才会出现，我一会儿增加错误日志吧。

**Comment by dompling** [comment]
> 我使用的是loon反复试了几次都是一样的结果

已经做了提示了，可以再试试看有提示不。
