### ISSUE TITLE
请问登录助手怎么添加账号呀

### ISSUE THREAD

**Issue by moxuan1121** [dompling/Script#5]
![image](https://user-images.githubusercontent.com/99877708/177696884-51fe9663-eeb4-429f-a5a5-2b4c1e36fbc9.png)
我不会可以教一下我吗

**Comment by dompling** [comment]
@moxuan1121 可以来tg看看视频教程

**Comment by moxuan1121** [comment]
> @moxuan1121 可以来tg看看视频教程

群在哪里呀

**Comment by dompling** [comment]
@moxuan1121 https://t.me/ScriptablePRO
