### ISSUE TITLE
10010.cookie在loon上无法获取

### ISSUE THREAD

**Issue by TychoSuen** [dompling/Script#6]
实测在qx上打开联通app能获取cookie并在boxjs中显示，loon上不提示获取同时boxjs中也没有cookie

**Comment by dompling** [comment]
> 
可能是配置没有写好，脚本应该是没问题的。

**Comment by TychoSuen** [comment]
![image](https://user-images.githubusercontent.com/76845019/182109136-fbff92a4-a819-448b-b847-2b56529e04b9.png)

**Comment by TychoSuen** [comment]
在loon里直接订阅这个可以吗？上面的内容都是在js中copy出来的

**Comment by dompling** [comment]
@TaiPresident 应该是不行的。

**Comment by dompling** [comment]
@TaiPresident 不过，你为什么要在 10010 里面获取联通的 cookie 呢？
